version: 2.1

jobs:
  test:
    docker:
      - image: cimg/clojure:1.11.1
    steps:
      - checkout
      - run: lein test
  deploy:
    docker:
      - image: cimg/clojure:1.11.1
    steps:
      - checkout
      - run: lein deploy

workflows:
  test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: /release/
          context: clojars